# Power BI Integration

> End-to-end pipeline connecting the Python ETL analysis to an interactive
> 4-page Power BI report covering company rankings, geographic distribution,
> industry analysis, and temporal trends with a 3-month rolling average.

---

## Architecture

```
layoffs.csv  (4,319 raw rows)
      │
      ▼
export_for_powerbi.py   ← Python (Pandas ETL)
      │
      ├── pbi_fact_layoffs.csv          (2,831 clean events)
      ├── pbi_company_rankings.csv      (top 30 companies)
      ├── pbi_country_summary.csv       (56 countries)
      ├── pbi_industry_summary.csv      (31 industries)
      ├── pbi_yearly_trend.csv          (2020–2026 yearly aggregates)
      └── pbi_rolling_trend.csv         (72 months + 3M rolling avg)
              │
              ▼
      Power BI Desktop
              │
              ├── Page 1 — Company Rankings
              ├── Page 2 — Geographic View
              ├── Page 3 — Industry Analysis
              └── Page 4 — Temporal Trends
```

The Python layer handles all cleaning, transformation, and aggregation.
Power BI consumes pre-modelled tables and applies DAX measures for KPI cards
and derived metrics.

---

## Running the Export

```bash
# From the repo root
pip install pandas numpy
python powerbi_integration/export_for_powerbi.py
```

`layoffs.csv` is loaded from the repo root. If absent, the script downloads
it from GitHub automatically. Output lands in `powerbi_integration/output/`.

---

## Loading into Power BI Desktop

1. Open Power BI Desktop → **Get Data → Text/CSV**
2. Import all 6 files from `powerbi_integration/output/`
3. In Power Query, set:
   - `date` columns → **Date/Time**
   - `year` → **Whole Number**
   - `total_laid_off`, `layoff_events`, `rank` → **Whole Number**
   - `pct_of_global`, `avg_pct_laid_off`, `yoy_pct_change` → **Decimal Number**
4. Click **Close & Apply**

No relationships needed — all tables are pre-aggregated and self-contained.

---

## DAX Measures

All measures are in `powerbi_integration/dax_measures.txt`.

Key measures:

| Page | Measure | Value |
|------|---------|-------|
| 1 | `Total Layoffs` | 840,000+ |
| 1 | `Top Company Layoffs` | 58,024 (Amazon) |
| 2 | `US Share of Global` | ~68% |
| 3 | `Hardware Avg Per Event` | 1,792 |
| 4 | `Peak Year Total` | 264,320 (2023) |
| 4 | `Rolling 3M Peak Label` | 153,967 — Jan 2023 |

---

## Report Pages

### Page 1 — Company Rankings
Horizontal bar chart of top 30 companies by total layoffs. Amazon leads
at 58,024 across 12 separate events. KPI cards show total companies affected,
events, and average layoffs per event. Industry and year slicers enable
on-demand filtering — matching the parameterized query approach in the notebook.

### Page 2 — Geographic View
Filled map showing global layoff distribution across 56 countries. The US
accounts for ~68% of all layoffs. A bar chart of the top 15 countries and
a donut of the top 5 provide three complementary geographic views.

### Page 3 — Industry Analysis
Two bar charts — total layoffs and average per event — reveal the difference
between frequency and severity. Hardware has the highest average cut size
(1,792 per event) while AI had only 1,532 total layoffs, reflecting active
expansion rather than contraction. A scatter plot plots frequency vs severity
for each industry.

### Page 4 — Temporal Trends
A dual-line chart overlays raw monthly layoffs against the 3-month rolling
average, smoothing volatility to reveal the January 2023 peak at 153,967.
A yearly column chart highlights 2023 as the peak year with 264,320 layoffs
driven by simultaneous cuts at Meta, Amazon, and Google.

---

## File Reference

```
powerbi_integration/
├── export_for_powerbi.py       # ETL pipeline → 6 Power BI tables
├── dax_measures.txt            # All DAX measures grouped by page
├── report_layout_spec.txt      # Visual-by-visual layout for all 4 pages
├── README_POWERBI.md           # This file
└── output/                     # Generated by export_for_powerbi.py
    ├── pbi_fact_layoffs.csv
    ├── pbi_company_rankings.csv
    ├── pbi_country_summary.csv
    ├── pbi_industry_summary.csv
    ├── pbi_yearly_trend.csv
    └── pbi_rolling_trend.csv
```
